#!/usr/bin/env bash
set -euo pipefail

: "${NERFSTUDIO_RDNA4_PUBLIC_PYTHON:?set NERFSTUDIO_RDNA4_PUBLIC_PYTHON}"
: "${NERFSTUDIO_RDNA4_PUBLIC_NERFSTUDIO_WORKTREE:?set NERFSTUDIO_RDNA4_PUBLIC_NERFSTUDIO_WORKTREE}"
: "${NERFSTUDIO_RDNA4_PUBLIC_TCNN_RUNTIME:?set NERFSTUDIO_RDNA4_PUBLIC_TCNN_RUNTIME}"
: "${NERFSTUDIO_RDNA4_PUBLIC_DATASET:?set NERFSTUDIO_RDNA4_PUBLIC_DATASET}"
: "${NERFSTUDIO_RDNA4_PUBLIC_OUTPUT_ROOT:?set NERFSTUDIO_RDNA4_PUBLIC_OUTPUT_ROOT}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
exec "$NERFSTUDIO_RDNA4_PUBLIC_PYTHON" \
  "$REPO_ROOT/tools/run_public_quick_validation_v1.py" \
  --python "$NERFSTUDIO_RDNA4_PUBLIC_PYTHON" \
  --nerfstudio-worktree "$NERFSTUDIO_RDNA4_PUBLIC_NERFSTUDIO_WORKTREE" \
  --tcnn-runtime "$NERFSTUDIO_RDNA4_PUBLIC_TCNN_RUNTIME" \
  --data "$NERFSTUDIO_RDNA4_PUBLIC_DATASET" \
  --output-root "$NERFSTUDIO_RDNA4_PUBLIC_OUTPUT_ROOT" \
  "$@"
