#!/usr/bin/env bash
set -euo pipefail

: "${NERFSTUDIO_RDNA4_PUBLIC_PYTHON:?set NERFSTUDIO_RDNA4_PUBLIC_PYTHON}"
: "${NERFSTUDIO_RDNA4_PUBLIC_OUTPUT_ROOT:?set NERFSTUDIO_RDNA4_PUBLIC_OUTPUT_ROOT}"
: "${NERFSTUDIO_RDNA4_PUBLIC_P0_RUN_DIR:?set NERFSTUDIO_RDNA4_PUBLIC_P0_RUN_DIR}"
: "${NERFSTUDIO_RDNA4_PUBLIC_P1_RUN_DIR:?set NERFSTUDIO_RDNA4_PUBLIC_P1_RUN_DIR}"
: "${NERFSTUDIO_RDNA4_PUBLIC_P2_RUN_DIR:?set NERFSTUDIO_RDNA4_PUBLIC_P2_RUN_DIR}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
exec "$NERFSTUDIO_RDNA4_PUBLIC_PYTHON" \
  "$REPO_ROOT/tools/run_public_a5_freeze_v1.py" \
  --p0-run-dir "$NERFSTUDIO_RDNA4_PUBLIC_P0_RUN_DIR" \
  --p1-run-dir "$NERFSTUDIO_RDNA4_PUBLIC_P1_RUN_DIR" \
  --p2-run-dir "$NERFSTUDIO_RDNA4_PUBLIC_P2_RUN_DIR" \
  --output-root "$NERFSTUDIO_RDNA4_PUBLIC_OUTPUT_ROOT" \
  "$@"
